SHELL = '/bin/sh'

COMPILE:
	printf '%s\n' "Python, no compilation."

RUN:
	printf '%s\n\n' "Refer to README.txt -> Execution section for instructions."

CLEAN:
	printf '%s\n' "Python, no cleanup necessary."